"""Turning a Google Maps place profile into citable evidence.

Reviews and the headline rating enter the same pipeline as every other source:
they're stored as `Evidence` with a real source URL, a real publication time
(each review's own post date), and a source type, so claims drawn from them are
cited and verified like any others. Nothing about them is paraphrased here.
"""

from __future__ import annotations

from datetime import datetime

from app.models.evidence import Evidence, SourceType
from app.models.place_profile import PlaceProfile
from app.tools.translation import META_LANGUAGE, META_ORIGINAL_TEXT, META_TRANSLATED_BY

# Which planned topic reviews are filed under. Claim extraction works per
# topic, so they have to land on one the plan actually contains.
_TOPIC_PREFERENCE = ("community_sentiment", "food", "nightlife", "nearby_amenities")


def pick_topic(topic_ids: list[str]) -> str | None:
    for preferred in _TOPIC_PREFERENCE:
        if preferred in topic_ids:
            return preferred
    return topic_ids[0] if topic_ids else None


def _headline(profile: PlaceProfile) -> str | None:
    parts = []
    if profile.rating is not None:
        count = f" from {profile.review_count:,} reviews" if profile.review_count else ""
        parts.append(f"Google Maps lists {profile.name} with an average rating of {profile.rating} out of 5{count}.")
    if profile.price_level:
        parts.append(f"Price level: {profile.price_level}.")
    if profile.summary:
        parts.append(profile.summary)
    return " ".join(parts) or None


def profile_to_evidence(
    profile: PlaceProfile, topic_id: str, location_scope: str, retrieved_at: datetime
) -> list[Evidence]:
    source_url = profile.maps_url or "https://www.google.com/maps"
    base = {
        "source_url": source_url,
        "publisher": "Google Maps",
        "source_type": SourceType.REVIEW_AGGREGATOR,
        "retrieved_at": retrieved_at,
        "location_scope": location_scope,
        "topic": topic_id,
        "relevance_score": 1.0,
    }

    items: list[Evidence] = []
    headline = _headline(profile)
    if headline:
        items.append(
            Evidence(
                evidence_id=f"google:{profile.place_id}:summary",
                source_title=f"Google Maps listing for {profile.name}",
                text=headline,
                metadata={"provider": "google_places", "is_fixture": "false"},
                **base,
            )
        )

    if profile.review_summary:
        disclosure = profile.review_summary_disclosure or "AI-generated by Google"
        count = f"{profile.review_count:,} " if profile.review_count else ""
        items.append(
            Evidence(
                evidence_id=f"google:{profile.place_id}:reviewsummary",
                source_title=f"Google Maps summary of {count}reviews of {profile.name}",
                text=f"Google's own summary of its {count}reviews ({disclosure}): {profile.review_summary}",
                metadata={"provider": "google_places", "is_fixture": "false", "generated_by": disclosure},
                **base,
            )
        )

    for index, review in enumerate(profile.reviews):
        metadata = {"provider": "google_places", "is_fixture": "false"}
        if review.original_text and review.original_language:
            metadata[META_LANGUAGE] = review.original_language
            metadata[META_ORIGINAL_TEXT] = review.original_text
            metadata[META_TRANSLATED_BY] = "machine translation (Google Maps)"
        stars = f"{review.rating}/5 stars. " if review.rating else ""
        items.append(
            Evidence(
                evidence_id=f"google:{profile.place_id}:review{index}",
                source_title=f"Google Maps review of {profile.name}"
                + (f" by {review.author}" if review.author else ""),
                text=f"{stars}{review.text}",
                published_at=review.published_at,
                metadata=metadata,
                **base,
            )
        )
    return items
